### ISSUE TITLE
Unable to use different layout for mermaid

### ISSUE THREAD

**Issue by dlouwers** [johanneswuerbach/backstage-plugin-techdocs-addon-mermaid#58]
My flow diagrams look terrible with the default layout but great with the `elk` one. I have changed the configuration to include:

```xml
<Mermaid config={{ layout: 'elk', theme: 'forest', themeVariables: { lineColor: '#000000' } }} />
```
Unfortunately this doesn't seem to have an effect, nor does the per diagram configuration:

```yaml
title: Triage
config:
    layout: elk
    look: handDrawn
    theme: dark
```
Is there a way to support selecting layouts?
